<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
        <PackageId>GoPaySDK</PackageId>
		<Version>1.2.1</Version>
		<Authors>Taalaibek</Authors>
		<Company>Taalaibek</Company>
		<Product>GoPay SDK</Product>
		<Description>GoPay KG SDK for .NET applications. Supports payments, payment cancellation, static QR codes, payment apps deep links, buyer contacts, fiscal receipt items, and typed webhooks (payment, invoice, subscription).</Description>
		<PackageTags>gopay;payments;kg;kyrgyzstan;dotnet;aspnetcore;qr;elqr</PackageTags>
		<RepositoryUrl>https://github.com/taalaibekdev/GoPay</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/taalaibekdev/GoPay</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

</Project>
